CREATE DATABASE IF NOT EXISTS P4;

USE P4;

-- Ejercicio 1

DROP TABLE IF EXISTS PARTICIPACION;
DROP TABLE IF EXISTS COMPETICION;
DROP TABLE IF EXISTS CLUB;

CREATE TABLE COMPETICION (
    `P#`            INT             NOT NULL            AUTO_INCREMENT,
    DESCRIPCION     CHAR(35)        NOT NULL,
    CATEGORIA       INT             NOT NULL,
    PRIMARY KEY (`P#`)
);

CREATE TABLE CLUB (
    `C#`            INT             NOT NULL            AUTO_INCREMENT,
    NOM_C           CHAR(35)        NOT NULL,
    PRESUPUESTO     INT             NOT NULL,
    PRIMARY KEY (`C#`)
);

CREATE TABLE PARTICIPACION (
    `P#`            INT             NOT NULL,
    `C#`            INT             NOT NULL,
    PUESTO          INT             NOT NULL,
    PRIMARY KEY (`P#`, `C#`),
    FOREIGN KEY (`P#`) REFERENCES COMPETICION (`P#`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`C#`) REFERENCES CLUB (`C#`) ON DELETE CASCADE ON UPDATE CASCADE 
);

INSERT INTO CLUB VALUES (DEFAULT, 'La Rejunta', 6000000);
INSERT INTO CLUB VALUES (DEFAULT, 'BM', 5100000);

INSERT INTO COMPETICION VALUES (DEFAULT, 'BM', 1);
INSERT INTO COMPETICION VALUES (DEFAULT, 'BM1', 2);
INSERT INTO COMPETICION VALUES (DEFAULT, 'BM2', 3);

INSERT INTO PARTICIPACION VALUES (1, 1, 1);
INSERT INTO PARTICIPACION VALUES (2, 1, 1);
INSERT INTO PARTICIPACION VALUES (3, 1, 1);
INSERT INTO PARTICIPACION VALUES (1, 2, 2);
INSERT INTO PARTICIPACION VALUES (2, 2, 2);

SELECT NOM_C FROM CLUB WHERE PRESUPUESTO > 5000000 AND `C#` IN
    (SELECT `C#` FROM PARTICIPACION WHERE `P#` IN
        (SELECT `P#` FROM COMPETICION WHERE CATEGORIA = 2));

SELECT NOM_C FROM CLUB WHERE 
    `C#` IN (SELECT `C#` FROM PARTICIPACION WHERE PUESTO = 1)
    AND
    `C#` NOT IN (SELECT `C#` FROM PARTICIPACION WHERE PUESTO > 1);

SELECT NOM_C FROM CLUB WHERE `C#` IN 
    (SELECT `C#` FROM PARTICIPACION GROUP BY `C#` HAVING COUNT(`P#`) = (SELECT COUNT(*) FROM COMPETICION));

SELECT NOM_C FROM CLUB WHERE 
    `C#` IN (SELECT `C#` FROM PARTICIPACION WHERE `P#` = 1)
    AND
    `C#` IN (SELECT `C#` FROM PARTICIPACION WHERE `P#` = 2);

SELECT NOM_C, PRESUPUESTO FROM CLUB WHERE
    `C#` NOT IN (SELECT `C#` FROM PARTICIPACION WHERE PUESTO = 1);

-- Ejercicio 2

DROP TABLE IF EXISTS PARTIDAS;
DROP TABLE IF EXISTS JUGADORES;
DROP TABLE IF EXISTS CAMPEONATOS;

CREATE TABLE JUGADORES (
    `J#`            INT             NOT NULL            AUTO_INCREMENT,
    NOMBRE          CHAR(35)        NOT NULL,
    NACIONALIDAD    CHAR(35)        NOT NULL,
    PRIMARY KEY (`J#`)
);

CREATE TABLE CAMPEONATOS (
    `C#`            INT             NOT NULL            AUTO_INCREMENT,
    NOM_C           CHAR(35)        NOT NULL,
    CATEGORIA       CHAR(35)        NOT NULL,
    PRIMARY KEY (`C#`)
);

CREATE TABLE PARTIDAS (
    `P#`            INT             NOT NULL            AUTO_INCREMENT,
    J1              INT             NOT NULL,
    J2              INT             NOT NULL,
    `C#`            INT             NOT NULL,
    FECHA           DATE            NOT NULL,
    RESULTADO       INT             NOT NULL,
    PRIMARY KEY (`P#`, J1, J2, `C#`),
    FOREIGN KEY (J1) REFERENCES JUGADORES (`J#`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (J2) REFERENCES JUGADORES (`J#`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`C#`) REFERENCES CAMPEONATOS (`C#`) ON DELETE CASCADE ON UPDATE CASCADE 
);

INSERT INTO JUGADORES VALUES (DEFAULT, 'BM', 'Argentina');
INSERT INTO JUGADORES VALUES (DEFAULT, 'JM', 'Argentina');
INSERT INTO JUGADORES VALUES (DEFAULT, 'PA', 'Irlanda');
INSERT INTO JUGADORES VALUES (DEFAULT, 'JC', 'EEUU');
INSERT INTO JUGADORES VALUES (DEFAULT, 'KT', 'LOL');

INSERT INTO CAMPEONATOS VALUES (DEFAULT, 'CMP1', 'Junior');
INSERT INTO CAMPEONATOS VALUES (DEFAULT, 'CMP2', 'Senior');
INSERT INTO CAMPEONATOS VALUES (DEFAULT, 'CMP3', 'Junior');
INSERT INTO CAMPEONATOS VALUES (7, 'CMP7', 'Junior');

INSERT INTO PARTIDAS VALUES (DEFAULT, 1, 2, 1, '2020-11-25', 1);
INSERT INTO PARTIDAS VALUES (DEFAULT, 1, 3, 1, '2020-11-26', 0);
INSERT INTO PARTIDAS VALUES (DEFAULT, 3, 2, 2, '2020-11-27', -1);
INSERT INTO PARTIDAS VALUES (DEFAULT, 1, 2, 3, '2020-11-28', -1);
INSERT INTO PARTIDAS VALUES (DEFAULT, 4, 2, 7, '2020-11-28', 1);

SELECT `P#`, FECHA, RESULTADO FROM PARTIDAS WHERE
    `C#` IN (SELECT `C#` FROM CAMPEONATOS WHERE CATEGORIA = 'Junior')
    AND
    (J1 IN (SELECT `J#` FROM JUGADORES WHERE NACIONALIDAD = 'Argentina')
    OR
    J2 IN (SELECT `J#` FROM JUGADORES WHERE NACIONALIDAD = 'Argentina'));

SELECT NOMBRE FROM JUGADORES WHERE
    `J#` IN (SELECT J1 FROM PARTIDAS WHERE `C#` = 1 OR `C#` = 7)
    OR
    `J#` IN (SELECT J2 FROM PARTIDAS WHERE `C#` = 1 OR `C#` = 7);

SELECT NOMBRE FROM JUGADORES WHERE
    EXISTS (SELECT * FROM PARTIDAS WHERE (`J#` = J1 OR `J#` = J2) AND `C#` = 1)
    AND
    EXISTS (SELECT * FROM PARTIDAS WHERE (`J#` = J1 OR `J#` = J2) AND `C#` = 7);

SELECT NOM_C FROM CAMPEONATOS, PARTIDAS, JUGADORES J1, JUGADORES J2 WHERE
    PARTIDAS.J1 = J1.`J#` AND PARTIDAS.J2 = J2.`J#` AND PARTIDAS.`C#` = CAMPEONATOS.`C#`
    AND J1.NACIONALIDAD = J2.NACIONALIDAD;

SELECT NOMBRE FROM JUGADORES WHERE
    `J#` NOT IN (SELECT DISTINCT J1 FROM PARTIDAS)
    AND
    `J#` NOT IN (SELECT DISTINCT J2 FROM PARTIDAS);

-- -- Ejercicio 3

-- DROP TABLE IF EXISTS MATRIMONIO;
-- DROP TABLE IF EXISTS PERSONA;

-- CREATE TABLE PERSONA (
--     NOMBRE          CHAR(35)        NOT NULL,
--     SEXO            CHAR(35)        NOT NULL,
--     FECHA_NAC       DATE            NOT NULL,
--     NOM_M           CHAR(35)        NOT NULL,
--     NOM_P           CHAR(35)        NOT NULL,
--     PRIMARY KEY (NOMBRE)
-- );

-- CREATE TABLE MATRIMONIO (
--     NOM_V           CHAR(35)        NOT NULL,
--     NOM_M           CHAR(35)        NOT NULL,
--     FECHA_INIC      DATE            NOT NULL,
--     FECHA_FIN       DATE            NOT NULL,
--     PRIMARY KEY (NOM_V, NOM_M),
--     FOREIGN KEY (NOM_V) REFERENCES PERSONA (NOMBRE) ON DELETE CASCADE ON UPDATE CASCADE,
--     FOREIGN KEY (NOM_M) REFERENCES PERSONA (NOMBRE) ON DELETE CASCADE ON UPDATE CASCADE
-- );

-- INSERT INTO PERSONA VALUES ('1', 'M', '2020-11-25', '', '');
-- INSERT INTO PERSONA VALUES ('2', 'F', '2020-11-25', '', '');
-- INSERT INTO PERSONA VALUES ('3', 'F', '2020-11-25', '', '');
-- INSERT INTO PERSONA VALUES ('4', 'M', '2020-11-23', '1', '2');
-- INSERT INTO PERSONA VALUES ('5', 'M', '2020-11-23', '1', '3');
-- -- INSERT INTO PERSONA VALUES ('6', 'M', '2020-11-25', '1', '3');

-- INSERT INTO MATRIMONIO VALUES('1', '2', '2020-11-25', '2020-11-26');
-- INSERT INTO MATRIMONIO VALUES('1', '3', '2020-11-27', '2020-11-28');

